/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parte2seguimiento3;

/**
 *
 * @author Asus
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCRadio = new javax.swing.JTextField();
        txtCArea = new javax.swing.JTextField();
        txtCPerimetro = new javax.swing.JTextField();
        txtRBase = new javax.swing.JTextField();
        txtRAltura = new javax.swing.JTextField();
        txtRPerimetro = new javax.swing.JTextField();
        txtRArea = new javax.swing.JTextField();
        btnCArea = new javax.swing.JButton();
        btnCPerimetro = new javax.swing.JButton();
        btnCBorrar = new javax.swing.JButton();
        btnRArea = new javax.swing.JButton();
        btnRPerimetro = new javax.swing.JButton();
        btnRBorrar = new javax.swing.JButton();
        txtCuaPerimetro = new javax.swing.JTextField();
        txtCuaLado = new javax.swing.JTextField();
        txtCuaArea = new javax.swing.JTextField();
        btnCuaArea = new javax.swing.JButton();
        btnCuaPerimetro = new javax.swing.JButton();
        btnCuaBorrar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTBase = new javax.swing.JTextField();
        txtTAltura = new javax.swing.JTextField();
        txtTPerimetro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtTArea = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtTHipotenusa = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtTTipo = new javax.swing.JTextField();
        btnTArea = new javax.swing.JButton();
        btnTPerimetro = new javax.swing.JButton();
        btnTHipotenusa = new javax.swing.JButton();
        btnTTipo = new javax.swing.JButton();
        btnTBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calculo figuras");

        jLabel2.setText("Circulo");

        jLabel3.setText("Radio");

        jLabel4.setText("Area");

        jLabel5.setText("Perimetro");

        jLabel6.setText("Base");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        jLabel9.setText("Altura");

        jLabel10.setText("Rectangulo");

        txtCArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCAreaActionPerformed(evt);
            }
        });

        txtRPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRPerimetroActionPerformed(evt);
            }
        });

        btnCArea.setText("Calcular area");
        btnCArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAreaActionPerformed(evt);
            }
        });

        btnCPerimetro.setText("Calcular perimetro");
        btnCPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPerimetroActionPerformed(evt);
            }
        });

        btnCBorrar.setText("Borrar");
        btnCBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBorrarActionPerformed(evt);
            }
        });

        btnRArea.setText("Calcular area");
        btnRArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAreaActionPerformed(evt);
            }
        });

        btnRPerimetro.setText("Calcular perimetro");
        btnRPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPerimetroActionPerformed(evt);
            }
        });

        btnRBorrar.setText("Borrar");
        btnRBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRBorrarActionPerformed(evt);
            }
        });

        txtCuaPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuaPerimetroActionPerformed(evt);
            }
        });

        txtCuaLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuaLadoActionPerformed(evt);
            }
        });

        btnCuaArea.setText("Calcular area");
        btnCuaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuaAreaActionPerformed(evt);
            }
        });

        btnCuaPerimetro.setText("Calcular perimetro");
        btnCuaPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuaPerimetroActionPerformed(evt);
            }
        });

        btnCuaBorrar.setText("Borrar");
        btnCuaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuaBorrarActionPerformed(evt);
            }
        });

        jLabel21.setText("Cuadrado");

        jLabel22.setText("Lado");

        jLabel23.setText("Area");

        jLabel24.setText("Perimetro");

        txtTAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAlturaActionPerformed(evt);
            }
        });

        txtTPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPerimetroActionPerformed(evt);
            }
        });

        jLabel25.setText("Altura");

        jLabel26.setText("Triangulo Rectangulo");

        jLabel27.setText("Base");

        jLabel28.setText("Area");

        jLabel29.setText("Perimetro");

        jLabel30.setText("Hipotenusa");

        txtTHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTHipotenusaActionPerformed(evt);
            }
        });

        jLabel31.setText("Tipo de triangulo");

        btnTArea.setText("Calcular area");
        btnTArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAreaActionPerformed(evt);
            }
        });

        btnTPerimetro.setText("Calcular perimetro");
        btnTPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPerimetroActionPerformed(evt);
            }
        });

        btnTHipotenusa.setText("Calcular hipoteusa");
        btnTHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHipotenusaActionPerformed(evt);
            }
        });

        btnTTipo.setText("Tipo de triangulo");
        btnTTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTipoActionPerformed(evt);
            }
        });

        btnTBorrar.setText("Borrar");
        btnTBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCArea)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTTipo)
                                        .addGap(64, 64, 64)
                                        .addComponent(btnTBorrar)
                                        .addGap(115, 115, 115))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(257, 257, 257)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(btnTArea)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnTPerimetro))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(232, 232, 232)
                                                .addComponent(jLabel26))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTBase)
                                                    .addComponent(txtTAltura)
                                                    .addComponent(txtTPerimetro)
                                                    .addComponent(txtTArea)
                                                    .addComponent(txtTHipotenusa)
                                                    .addComponent(txtTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(78, 78, 78)))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnTHipotenusa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCPerimetro)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnCBorrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRArea)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnRPerimetro)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnRBorrar)))
                                .addGap(64, 64, 64))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCPerimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtCArea)
                                    .addComponent(txtCRadio))
                                .addGap(212, 212, 212)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRArea, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCuaArea)
                                .addGap(29, 29, 29)
                                .addComponent(btnCuaPerimetro)
                                .addGap(40, 40, 40)
                                .addComponent(btnCuaBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuaLado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCuaArea)
                                        .addComponent(txtCuaPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtRArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRArea)
                            .addComponent(btnRPerimetro)
                            .addComponent(btnRBorrar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCArea)
                        .addComponent(btnCPerimetro)
                        .addComponent(btnCBorrar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel21)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtCuaLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtCuaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuaPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCuaArea)
                            .addComponent(btnCuaPerimetro)
                            .addComponent(btnCuaBorrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtTHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTArea)
                            .addComponent(btnTPerimetro)
                            .addComponent(btnTHipotenusa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTTipo)
                            .addComponent(btnTBorrar))))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCAreaActionPerformed

    private void btnCPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPerimetroActionPerformed
        try {
            double radio = Double.parseDouble(txtCRadio.getText());
            Circulo circulo = new Circulo(radio);
            txtCPerimetro.setText(circulo.calcularPerimetro());
        } catch (NumberFormatException e) {
            txtCPerimetro.setText("Por favor ingrese un valor numerico valido");
        }
    }//GEN-LAST:event_btnCPerimetroActionPerformed

    private void btnCBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBorrarActionPerformed
        
        txtCRadio.setText("");
        txtCArea.setText("");
        txtCPerimetro.setText("");
        
    }//GEN-LAST:event_btnCBorrarActionPerformed

    private void btnRPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPerimetroActionPerformed
        
        try {
            double base = Double.parseDouble(txtRBase.getText());
            double altura = Double.parseDouble(txtRAltura.getText());
            Rectangulo rectangulo = new Rectangulo(base, altura);
            txtRPerimetro.setText(rectangulo.calcularPerimetro());
        } catch (NumberFormatException e) {
            txtRPerimetro.setText("Por favor ingrese un valor numerico valido");
        }
        
    }//GEN-LAST:event_btnRPerimetroActionPerformed

    private void btnRBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRBorrarActionPerformed
        
        txtRBase.setText("");
        txtRAltura.setText("");
        txtRArea.setText("");
        txtRPerimetro.setText("");
        
    }//GEN-LAST:event_btnRBorrarActionPerformed

    private void txtCuaLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuaLadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuaLadoActionPerformed

    private void btnCuaPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuaPerimetroActionPerformed
        
        try {
            double lado = Double.parseDouble(txtCuaLado.getText());
            Cuadrado cuadrado = new Cuadrado(lado);
            txtCuaPerimetro.setText(cuadrado.calcularPerimetro());
        } catch (NumberFormatException e) {
            txtCuaPerimetro.setText("Por favor ingrese un valor valido");
        }
        
        
    }//GEN-LAST:event_btnCuaPerimetroActionPerformed

    private void btnCuaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuaBorrarActionPerformed
        
        txtCuaLado.setText("");
        txtCuaArea.setText("");
        txtCuaPerimetro.setText("");
        
    }//GEN-LAST:event_btnCuaBorrarActionPerformed

    private void btnTAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAreaActionPerformed
        
        try {
            double base = Double.parseDouble(txtTBase.getText());
            double altura = Double.parseDouble(txtTAltura.getText());
            TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
            txtTArea.setText(String.valueOf(triangulo.calcularArea()));
        } catch (NumberFormatException e) {
            txtTArea.setText("Por favor ingrese un valor valido");
        }
        
    }//GEN-LAST:event_btnTAreaActionPerformed

    private void btnTPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPerimetroActionPerformed
        
        try {
            double base = Double.parseDouble(txtTBase.getText());
            double altura = Double.parseDouble(txtTAltura.getText());
            TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
            txtTPerimetro.setText(String.valueOf(triangulo.calcularPerimetro()));
        } catch (NumberFormatException e) {
            txtTPerimetro.setText("Por favor ingrese un valor valido");
        }
       
    }//GEN-LAST:event_btnTPerimetroActionPerformed

    private void txtCuaPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuaPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuaPerimetroActionPerformed

    private void txtTAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTAlturaActionPerformed

    private void txtTPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTPerimetroActionPerformed

    private void txtTHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTHipotenusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTHipotenusaActionPerformed

    private void btnCAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAreaActionPerformed
        try {
            double radio = Double.parseDouble(txtCRadio.getText());
            Circulo circulo = new Circulo(radio);
            txtCArea.setText(circulo.calcularArea());
        } catch (NumberFormatException e) {
            txtCArea.setText("Por favor ingrese un valor numerico valido");
        } 
    }//GEN-LAST:event_btnCAreaActionPerformed

    private void btnRAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAreaActionPerformed
        
        try {
            double base = Double.parseDouble(txtRBase.getText());
            double altura = Double.parseDouble(txtRAltura.getText());
            Rectangulo rectangulo = new Rectangulo(base, altura);
            txtRArea.setText(rectangulo.calcularArea());
        } catch (NumberFormatException e) {
            txtRArea.setText("Por favor ingrese un valor numerico valido");
        }

    }//GEN-LAST:event_btnRAreaActionPerformed

    private void btnCuaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuaAreaActionPerformed
        
        try {
            double lado = Double.parseDouble(txtCuaLado.getText());
            Cuadrado cuadrado = new Cuadrado(lado);
            txtCuaArea.setText(cuadrado.calcularArea());
        } catch (NumberFormatException e) {
            txtCuaArea.setText("Por favor ingrese un valor valido");
        }
        
    }//GEN-LAST:event_btnCuaAreaActionPerformed

    private void btnTHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHipotenusaActionPerformed
        
        try {
            double base = Double.parseDouble(txtTBase.getText());
            double altura = Double.parseDouble(txtTAltura.getText());
            TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
            txtTHipotenusa.setText(String.valueOf(triangulo.calcularHipotenusa()));
        } catch (NumberFormatException e) {
            txtTHipotenusa.setText("Por favor ingrese un valor valido");
        }
        
    }//GEN-LAST:event_btnTHipotenusaActionPerformed

    private void btnTTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTipoActionPerformed
        
        try {
            double base = Double.parseDouble(txtTBase.getText());
            double altura = Double.parseDouble(txtTAltura.getText());
            TrianguloRectangulo triangulo = new TrianguloRectangulo(base, altura);
            txtTTipo.setText(String.valueOf(triangulo.determinarTipoTriangulo()));
        } catch (NumberFormatException e) {
            txtTTipo.setText("Por favor ingrese un valor valido");
        }
        
    }//GEN-LAST:event_btnTTipoActionPerformed

    private void btnTBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBorrarActionPerformed
        
        txtTBase.setText("");
        txtTAltura.setText("");
        txtTArea.setText("");
        txtTPerimetro.setText("");
        txtTHipotenusa.setText("");
        txtTTipo.setText("");
        
    }//GEN-LAST:event_btnTBorrarActionPerformed

    private void txtRPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRPerimetroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCArea;
    private javax.swing.JButton btnCBorrar;
    private javax.swing.JButton btnCPerimetro;
    private javax.swing.JButton btnCuaArea;
    private javax.swing.JButton btnCuaBorrar;
    private javax.swing.JButton btnCuaPerimetro;
    private javax.swing.JButton btnRArea;
    private javax.swing.JButton btnRBorrar;
    private javax.swing.JButton btnRPerimetro;
    private javax.swing.JButton btnTArea;
    private javax.swing.JButton btnTBorrar;
    private javax.swing.JButton btnTHipotenusa;
    private javax.swing.JButton btnTPerimetro;
    private javax.swing.JButton btnTTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCArea;
    private javax.swing.JTextField txtCPerimetro;
    private javax.swing.JTextField txtCRadio;
    private javax.swing.JTextField txtCuaArea;
    private javax.swing.JTextField txtCuaLado;
    private javax.swing.JTextField txtCuaPerimetro;
    private javax.swing.JTextField txtRAltura;
    private javax.swing.JTextField txtRArea;
    private javax.swing.JTextField txtRBase;
    private javax.swing.JTextField txtRPerimetro;
    private javax.swing.JTextField txtTAltura;
    private javax.swing.JTextField txtTArea;
    private javax.swing.JTextField txtTBase;
    private javax.swing.JTextField txtTHipotenusa;
    private javax.swing.JTextField txtTPerimetro;
    private javax.swing.JTextField txtTTipo;
    // End of variables declaration//GEN-END:variables
}
